- lib/fauxpaas/capistrano_deployer.rb
Simply cleanups CapistranoDeployer by extracting methods
> Extract CapistranoDeployer functionality to methods

- deploy/instances/test-norails/instance.yml
- deploy/instances/test-norails/releases.yml
- deploy/instances/test-rails/instance.yml
- lib/fauxpaas/file_instance_repo.rb
- spec/file_instance_repo_spec.rb
This PR simply moves the logging to a separate file in the instance storage dir, releases.yml. 
Resolves AEID-130
> Log releases in a separate file from instance.yml

- lib/fauxpaas.rb
- lib/fauxpaas/cli/main.rb
- lib/fauxpaas/components.rb
- lib/fauxpaas/verbose_system_runner.rb
- spec/verbose_system_runner_spec.rb
Closes AEID-129.
One thing to consider is how you feel about `Fauxpaas.system_runner=`. If you have another thought for how that should work, let me know... There is a potential issue where ordering matters - if the `backend_runner` gets constructed in components before you set the `system_runner`, the `backend_runner` doesn't get updated. That isn't trivial to fix, because even if you added a `backend_runner=` method you wouldn't necessarily know how the previous backend runner was created in order to build a new one with the new system runner... I don't know if this is important enough to address now, but either way I'm interested in your thoughts on how the top-level config could work.
CLI::Main is starting to get a bit ugly, but it has no tests. I'll take a look at addressing that …
> verbose option

- deploy/cap/restart.rb
- deploy/cap/syslog.rb
- deploy/deploy.rb
- lib/fauxpaas.rb
- lib/fauxpaas/cap.rb
- lib/fauxpaas/cap_runner.rb
- lib/fauxpaas/cli/main.rb
- lib/fauxpaas/cli/syslog.rb
- lib/fauxpaas/kernel_system.rb
- lib/fauxpaas/verbose_runner.rb
- spec/cap_runner_spec.rb
- spec/cap_spec.rb
- spec/cli/main_spec.rb
- spec/cli/syslog_spec.rb
- spec/support/mock_instance.rb
- spec/verbose_runner_spec.rb
Closes AEID-96.
We should be able to use a very similar approach for AEID-95.
> AEID-96 - developer can view journalctl log

- lib/fauxpaas/cli/main.rb
- spec/cli/main_spec.rb
* Adds a restart command as the final step in deployment
* Ensures that success/fail output is generated for the deploy and the
restart
* Does not run on failed deploys
* Works with test-norails
* Allows test-rails to successfully deploy, but fail to restart
* Resolves AEID-108
* Resolves AEID-127
> AEID-108 - Add restart to the end of successful deploys

- lib/fauxpaas/cap.rb
- lib/fauxpaas/components.rb
- lib/fauxpaas/components/backend_runner.rb
- lib/fauxpaas/components/git_runner.rb
- lib/fauxpaas/components/instance_repo.rb
- lib/fauxpaas/components/paths.rb
- lib/fauxpaas/components/system_runner.rb
- lib/fauxpaas/components/token.rb
- lib/fauxpaas/deploy_config.rb
- lib/fauxpaas/git_reference.rb
- spec/archive_spec.rb
- spec/cap_spec.rb
- spec/cli/main_spec.rb
- spec/deploy_config_spec.rb
- spec/file_instance_repo_spec.rb
- spec/instance_spec.rb
This helps to prevent circular dependencies, and makes the dependencies
on components more clear.
> Decompose components.rb

- lib/fauxpaas.rb
- lib/fauxpaas/passthrough_runner.rb
- spec/passthrough_runner_spec.rb
Adds PassthroughRunner, which runs the command while streaming the
output. Used in verbose mode.
> Re-enable verbose output from git and cap commands

- deploy/cap/commands.rb
- lib/fauxpaas/cap.rb
- lib/fauxpaas/cli/main.rb
- lib/fauxpaas/command.rb
- lib/fauxpaas/policy.rb
- spec/cap_spec.rb
- spec/command_spec.rb
- spec/policy_spec.rb
Resolves AEIM-1305
This PR is set to merge to master.
This is primarily to address a need for running intermittent commands
on deployed instances. See AE-3912.
Also includes a fix in `Policy#role?` that would cause an error if an action:roles pair were not defined.
> Add exec command

- deploy/cap/shared.rb
- deploy/cap/unshared.rb
- spec/integration_spec.rb
Resolves AEIM-1316
The point here is that the entirety of the deployed directory structure should be fully editable by anyone within the group, and completely locked down otherwise. 
Specifically, I would like someone to confirm that I'm testing for the correct octal permissions.
> Allow group read/write of deployed files and dirs

- deploy/cap/shared.rb
- deploy/cap/unshared.rb
- deploy/deploy.rb
- spec/integration_spec.rb
See AEIM-1318
* Adds several integration tests for proper permissions
* Fixes find-powered chmods in shared.rb, unshared.rb
* Sets permissions on public files at the end of the build, in deploy.rb
---
This PR required changes to the fixtures, which must be `git pull`'d in order to run the integration tests. The unit tests are unaffected.
> Correctly set permissions on public directories

- deploy/cap/source.rb
- deploy/capfiles/norails.capfile
- deploy/capfiles/rails.capfile
- deploy/deploy.rb
- lib/fauxpaas/cap.rb
- lib/fauxpaas/dir_only_scm.rb
- lib/fauxpaas/release.rb
- lib/fauxpaas/release_builder.rb
- spec/cap_spec.rb
- spec/fixtures/integration/capfiles/norails.capfile
- spec/fixtures/integration/capfiles/rails.capfile
- spec/release_builder_spec.rb
- spec/release_spec.rb
Resolves AEIM-1354
* Cap uses source_path instead of source
* Release uses source_path instead of source
* ReleaseBuilder uses source_path instead of source
* Add source upload to cap w/o scm
* Capfiles no longer download source with an SCM
* Remove now-unused CopySCM
> Download source directly instead of via capistrano

- Gemfile.lock
- deploy/cap/source.rb
- fauxpaas.gemspec
Uses the ruby-rsync gem to upload instead of sshkit
Resolves AEIM-1530
Compare to #64 
The merit of continuing to do this step in deploy/cap/source.rb is that it is clearer than relying on capistrano's inner SCM machinery. The hope is that will allow us to more easily remove capistrano eventually.
> Use rsync to upload files

- DESIGN.md
- Gemfile.lock
- deploy/capfiles/norails.capfile
- deploy/capfiles/rails.capfile
- deploy/deploy.rb
- fauxpaas.gemspec
- lib/fauxpaas/artifact_builder.rb
- spec/artifact_builder_spec.rb
- spec/fixtures/integration/capfiles/norails.capfile
- spec/fixtures/integration/capfiles/rails.capfile
- spec/fixtures/integration/repos/norails/source/Gemfile
- spec/fixtures/integration/repos/norails/source/Gemfile.lock
- spec/integration_spec.rb
This doesn't do anything with caching because bundler does that automatically as long as it's set up with a cache on the build server—so that's more a job for puppet. Unless anyone thinks there's a case for fauxpaas to know details about how the build server is set up as a whole?
Also I'm not sure if I was right to add an exception in the case of a bundle error. If we have other sanity checks that make the exception redundant, then I should definitely remove it.
> AEIM-1363 - Run bundle install after adding references

- Gemfile.lock
- deploy/capfiles/norails.capfile
- deploy/capfiles/rails.capfile
- deploy/deploy.rb
- fauxpaas.gemspec
- spec/fixtures/integration/capfiles/norails.capfile
- spec/fixtures/integration/capfiles/rails.capfile
While we're precompiling assets or running migrations with Cap, it needs
capistrano-bundler, or bundle exec is omitted and rake can throw errors.
> AEIM-1539 - Reintroduce capistrano-bundler

- config/settings.yml
- lib/fauxpaas.rb
- lib/fauxpaas/file_instance_repo.rb
- spec/file_instance_repo_spec.rb
- spec/fixtures/integration/instances/test-norails/hosts.rb
- spec/fixtures/integration/instances/test-rails/hosts.rb
- spec/integration_spec.rb
This is a combination of some effort to simplify DeployConfig's needs in AEIM-1366, and an effort to get the integration tests to run in capistrano. They still don't, but this at least cleans them up a bit.
> Cleaner integration tests

- Gemfile.lock
- lib/moku/artifact.rb
- lib/moku/cached_bundle.rb
- lib/moku/filesystem.rb
- lib/moku/release.rb
- lib/moku/task/shell.rb
- spec/artifact_spec.rb
- spec/cached_bundle_spec.rb
- spec/task/shell_spec.rb
* Resolves remaining issues with running under ruby 2.5
* Fixed an issue where unused gems from a different ruby version were being added to the artifact.
* Set Task::Shell to run in the context of the artifact via `#run` instead of `#with_env`, removing the need for its own runner.
* Set CachedBundle to run in the context of the artifact via `#run` instead of `#with_env`, removing the need for its own runner.
* Fixed an issue where remote tasks failed in test because we didn't set rbenv version, and could not rely on the remote host to set it for us.
* Also fixes the super weird travis issue,  via the bundle update.
> Various fixes

- lib/moku/command/rollback.rb
- lib/moku/instance.rb
- lib/moku/logged_releases.rb
- lib/moku/pipeline/rollback.rb
- spec/integration/deploy_spec.rb
- spec/integration/releases_spec.rb
Resolves AEIM-577
Now that the groundwork is in place this ended up being quite simple. The tests could be more specific but I wanted to avoid brittleness as much as was possible.
> AEIM-577: Treat rollbacks as releases

- config/settings.yml
- lib/moku.rb
- lib/moku/artifact_repo.rb
- lib/moku/pipeline/deploy.rb
- spec/support/with_a_sandbox.rb
* Adds branches_root to settings.yml
* No longer build artifacts in temp
* Add ArtifactRepo
* Avoid rebuilding successfully built artifacts, as identified by
signature
* Purge artifacts beyond some limit (to avoid filling up disk)
> Cache artifacts and avoid building artifacts in the system temp dir

- lib/moku/plan/basic_deploy.rb
- lib/moku/task/enable.rb
Resolves AEIM-1161
* Adds Task::Enable, which enables an instance's systemd services
* Adds Task::Enable to Plan::BasicDeploy#finish
There were a couple sensible locations to put this task.
> Enable in systemd on deploy

- lib/moku/release.rb
This reverts commit 0b101367d1aea0f80d550373086b772e86b7044d.
I had originally removed this code as it seemed to no longer be
necessary. That determination was premature.
Even now, I seem to only need this some of the time.
> Revert "Remove Release#rbenv_env use in Release#run"

- lib/moku/pipeline/deploy.rb
Resolves AEIM-1834
I tested this manually by populating the releases directory then letting the normal processes run. I could create a test that does the same if the reviewer thinks it is necessary. That would require expanding the test harness significantly. I don't expect `cleanup_caches` to change any time soon.
> Cleanup caches with just one command

- lib/moku/cli.rb
Resolves AEIM-1900
Enables GLI's strict argument checking and subcommand option
namespacing. The latter doesn't affect us, but is required by
the former.
Since there are no tests that exercise the cli, we need to test this by hand. Or say yolo.
> Fail fast when command line arguments are missing

- lib/moku/plan/basic_build.rb
- lib/moku/task/validate_pin.rb
- lib/moku/validator/gemfile.rb
- lib/moku/validator/ruby_version.rb
- lib/moku/validator/validator.rb
- spec/task/validate_pin_spec.rb
Resolves AEIM-1704
This adds Task::ValidatePin to Plan::BasicBuild, it performs the following checks:
* There is a .ruby-version present
* It specifies only a major version (e.g. 2.5)
* If the Gemfile includes a 'ruby' directive, it should specify only a major version.
Additionally, this adds:
* Validator::RubyVersion
* Validator::Gemfile
These two files do not have unit tests as they are currently
implementation details of Task::ValidatePin.
> Require pinning to major.minor ruby version

- Gemfile.lock
- lib/moku.rb
- lib/moku/deploy_config.rb
- lib/moku/plan/basic_deploy.rb
- lib/moku/release.rb
- lib/moku/shell/remote_release.rb
- lib/moku/task/symlink.rb
- moku.gemspec
- spec/deploy_config_spec.rb
- spec/fixtures/integration/repos/norails/infrastructure/sites/local_site/infrastructure.yml
- spec/integration/deploy_spec.rb
- spec/release_spec.rb
- spec/shell/remote_release_spec.rb
I experimented with a couple strategies here, which are spelled out in the commit messages. 0bf399a is a byproduct of that effort, but I have chosen to include it here anyway. The strategy I went with was to more or less use brute force, as can be seen in `Task::Symlink`. 
I think the correct strategy is to obviate the need to create these symlinks during the release phase altogether. The reason we can do that in the build phase now is site-specific files have not yet been moved into position. This saves us some file IO, at the cost of complexity. I think the best thing to do would be to build multiple artifacts, one for each host, possibly via hardlinks, towards the end of the build phase after the most costly operations (bundle, asset compilation) have been performed.
> AEIM-2033 Symlink paths from infrastructure.yml

- lib/moku/shell/basic.rb
- lib/moku/shell/passthrough.rb
- lib/moku/shell/secure_remote.rb
- spec/integration/deploy_spec.rb
- spec/support/realistic_remote_runner.rb
- spec/support/with_a_sandbox.rb
* Changes Shell::SecureRemote to use base64 encoding, thus solving for
whitespace and quotes in user-submitted commands.
* Adds the support class RealisticRemoteRunner, a subclass of
Shell::SecureRemote that always connects to localhost as the current
user, and also provides the path manipulation of FakeRemoteRunner.
* Uses the above when SSH=1 is passed to the integration tests.
* Adds the ability to pass an optional message to Shell::Basic#run and
Shell::Passthrough#run, to be displayed instead of the command. This
feature is used by Shell::SecureRemote to avoid displaying the command
in its encoded form.
> AEIM-2033 - Use base64 encoding in remote runners

- lib/moku/task/build_permissions.rb
- lib/moku/task/create_structure.rb
- spec/integration/deploy_spec.rb
- spec/support/a_successful_deploy.rb
We're working toward accommodating local-disk-only deployments with no
human users on the servers. This simplifies the file modes to some
degree and corresponds to a puppet provisioning change to support the
app user's home directory being the deployment target.
There is an open question of whether these modes are exactly right.
Specifically, is 740 right for binaries, or should they be 750?
> AEIM-2056 - Simplify permissions on the way to local disk

- lib/moku/task/symlink.rb
This ensures there is no newline after the command.
> Strips the last newline from the command in Task::Symlink

- lib/moku/plan/basic_build.rb
minimum change to allow "teeny" pinned deployments
> Disable check that blocks teeny ruby version pinning

- lib/moku/cached_bundle.rb
Running `bundle install --deployment` is deprecated.
> AE-9972 - Run bundle config set instead of --deployment
